using System.Collections.Generic;

namespace AbbaGame
{
    public sealed class StrongTestsExecutor : TestsExecutor
    {
        private StrongTestsExecutor()
        {
        }

        public override List<(string Initial, string Target, string Result)> Cases { get; } = new List<(string Initial, string Target, string Result)>
        {
            ("A", "ABBBABAAABAAB", POSSIBLE),
            ("A", "ABBBABAAABAABAAAAAAAAAAAAAAAAA", POSSIBLE),
            ("B", "ABBBABAAABAABAAAAAAAAAAAAAAAAAAAAAAA", IMPOSSIBLE),
            ("AABA", "ABABBABAAABABBAAABAABAABABAAABBAABBBBAABBBBBABBABBAABBAABAAABABABBBBBBBBBBBAABBABABBABAAAABBBBBABAAAABBB", POSSIBLE),
            ("AABA", "ABABBABAAABABBAAABAABAABABAAABBAABBBBAABBBBBABBABBAABBAABAAABABABBBBBBBBBBBAABBABABBABAAAABBBBBABAAAABBBAABBBBBBBBBBBBBBBBBBBBB", IMPOSSIBLE),
            ("ABBABAAABABBAAABAABAABABAAABBAABBBBAABBBBBABBABBAABBAABAAABABABBBBBBBBBBBAABBABABBABAAAABBBBBABAAAABB", "ABABBABAAABABBAAABAABAABABAAABBAABBBBAABBBBBABBABBAABBAABAAABABABBBBBBBBBBBAABBABABBABAAAABBBBBABAAAABBB", POSSIBLE),
        };

        public static TestsExecutor Instance => new StrongTestsExecutor();
    }
}
